name: DA - Pillar 3 - Release tests
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release_branch:
        type: string
        required: false

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

env:
  BRANCH_NAME: ${{ inputs.release_branch || github.ref_name }}
  REF: ${{ inputs.release_branch || github.ref_name }}


jobs:
  da_pillar3_release_lambda_unit_tests:
    name: Unit Tests [Lambda]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}

      - name: Print release_branch parameter
        run: |
          echo "Running Tests in Branch: ${{ env.REF }}"
