name: DA - UI deploy
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment [dev|integration]"
        required: true
        type: choice
        options:
          - dev
          - integration
  # Called from another workflow
  workflow_call:
    inputs:
      env:
        description: "Environment [dev|integration|preprod|prod]"
        type: string
        required: true
        default: "dev"
      release_branch:
        type: string
        required: true

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v4

env:
  AWS_REGION: eu-west-1
  TERRAFORM_VERSION: 1.5.7
  ENV: ${{ inputs.env || 'dev' }}
  REF: ${{ inputs.release_branch || github.ref_name }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: ./data_acquisition/infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}

      - name: Print Commit SHA
        run: |
          echo "${{ github.sha }}"
